module WelcomeHelper
    def get_product_card
        return array = [
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/xl7-3.png", title: "XL 7", price: "Mulai Rp. 230 juta", text: "GEAR TO ACCOMPLISH Suzuki XL7 hadir dengan tampilan maskulin, tangguh dan berkarakter. Desain modern SUV 7-Seater memberikan kebanggan dan kepercayaan bagi penggunanya. Dilengkapi dengan fitur canggih semakin membuat XL7 menjadi SUV yang luar biasa di kelasnya"},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/ertigaa.png", title: "Ertiga", price: "Mulai Rp. 205 juta", text: "Mobil Suzuki All New Ertiga Lebih Panjang, Lebih Lebar, Lebih Nyaman. All-New Ertiga kembali menjadi kekuatan Suzuki dalam pertarungan segmen Low MPV dan berhasil menjadi Mobil MPV terbaik 2019 Versi Media Otomotif."},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/ignis-1.png", title: "Ignis", price: "Mulai Rp. 181 Juta", text: "New IGNIS hadirkan desain baru bercita rasa SUV yang sporty dan stylish. Membuatnya tampil menonjol di antara para pesaingnya. Memasuki kabin IGNIS, kesan lapang, modern, unik, futuristik, dan nyaman langsung terasa. Ditambah lagi detail-detail berkelas dan sporty."},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/SCross-1.jpg", title: "SX4 S-Cross", price: "Mulai Rp. 305 juta", text: "Hidup Anda kini semakin lengkap dengan kehadiran crossover premium terbaru yang tetap memadukan kepuasan berkendara khas sedan serta ketangguhan SUV New SX4 S-CROSS tampil lebih gagah dengan desain eksterior baru yang solid tanpa meninggalkan kesan premium yang selama ini telah hadir. New SX4 S-CROSS, Gear to Explore!"},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/APV-1.jpg", title: "APV", price: "Mulai Rp. 162 juta", text: "Suzuki New APV Luxury dengan desain dan fitur istimewa menghadirkan indahnya kenyamanan dalam kemewahan untuk Anda dan keluarga. Desain baru pada eksterior dan interiornya berkesan elegan dengan beragam fungsi, kenyamanan serta kemewahan yang berpadu sangat indah menjadikan APV New Luxury tak lekang oleh waktu."},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/New-Baleno-1.jpg", title: "New Baleno", price: "Mulai Rp. 246 juta", text: "Tampil berkelas bersama New Baleno dengan desain terbaru yang begitu menawan di setiap sisinya. Dilengkapi fitur terbaru menjadikannya hatchback yang lengkap dan berkelas membuat aktivitas berkendara Anda semakin dinamis. New Baleno, Gear to Define"},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/Karimun-Wagon-R-1.jpg", title: "Wagon R", price: "Mulai Rp. 143 juta", text: "Temukan kemewahan gaya Anda bersama Karimun Wagon R GS. Detail yang impresif, modern, dan stylish mengundang decak kagum cerminan karakter diri Anda sesungguhnya."},
            {image: "https://suzukiuntukbdg.com/wp-content/uploads/2021/08/Untitled-2.jpg", title: "New Carry PU", price: "Mulai Rp. 156 juta", text: "Suzuki New Carry Pickup kini hadir dengan tampilan baru yang lebih segar dan semakin tangguh. Kemampuannya dalam menjelajahi berbagai macam medan menjadi inspirasi untuk tampilan dan kinerja Suzuki New Carry Pick Up yang lebih tangguh dari sebelumnya."}
        ]
    end
end
